# Module Test Template

## 1. Module & Test Description

This notebook is used for testing the concrete area aggregation functionality in *concrete.py*

### Imports
##### General Imports

In [1]:
import os, sys, pathlib
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import scipy as sc
import shapely as sh

import math

##### Extend PYPATH to current folder:
This allows importing libraries from the same folder; <code>pathlib.Path().resolve()</code> returns the path of the current directory.

In [2]:
sys.path.extend([pathlib.Path().resolve()])

Import specific testing modules:

In [3]:
# import concrete

## Testing Inputs
Below are the properties of several concrete regions, which we'l use for testing subsequent functions.

In [4]:
# Test inputing concrete regions as a 0D (single value), numpy array and python list:
as_float = 10.0
as_int = 5
as_list = [[10, 1], [1, 10], [2, 5]]

as_ndarray = np.array([[10, 1], [1, 10], [2, 5]])
as_0darray = np.array(5)
as_1darray = np.array([5, 2, 3, 4])
as_2darray = np.copy(as_ndarray)

In [5]:
# Return the type
type(as_float), type(as_int), type(as_list), type(as_ndarray)

(float, int, list, numpy.ndarray)

### Test dimensionality of lists and arrays

In [6]:
# For lists use a cheat:
def list_dims(my_list):
    if type(my_list) == list:
        temp = np.array(my_list)
        return temp.shape
    else:
        return 'Not a list type'

In [7]:
list_dims(as_list)

(3, 2)

In [8]:
def is_list(my_list):
    if type(my_list) == list:
        return True
    else:
        return False

In [9]:
is_list(as_list)

True

In [10]:
# Let's create a function that converts a python list to a numpy list

In [11]:
# Now let's make sure we have numpy arrays:
type(as_0darray), type(as_1darray), type(as_2darray), type(as_ndarray)

(numpy.ndarray, numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [12]:
# Now let's look at the shape of several numpy arrays
as_0darray.shape, as_1darray.shape, as_2darray.shape, as_ndarray.shape

((), (4,), (3, 2), (3, 2))

In [15]:
# Create a function turn a 0D array into at least a 1D array
def to_numpy(my_0Darray):
    if type(my_0Darray) == np.ndarray and my_0Darray.shape == ():
        return np.array([my_0Darray])
    else:
        return np.array(my_0Darray)

**WARNING:** Note that the conditional tests for the shorthand module name *np.ndarray* while type() returns *numpy.ndarray* 

In [16]:
to_numpy(as_0darray), to_numpy(as_1darray), to_numpy(as_ndarray), to_numpy(as_list)

(array([5]),
 array([5, 2, 3, 4]),
 array([[10,  1],
        [ 1, 10],
        [ 2,  5]]),
 array([[10,  1],
        [ 1, 10],
        [ 2,  5]]))

In [18]:
to_numpy(as_0darray).shape, to_numpy(as_1darray).shape, to_numpy(as_ndarray).shape, to_numpy(as_list).shape

((1,), (4,), (3, 2), (3, 2))

## Rescale a Value with a New Range
Create function that rescales a value that lies within a given range, to new range. By default the new range will be 0 -> 1. If <code>is_strict == True</code>, the function returns the new range min or max value, when the rescaled value occurs out of bounds.

In [ ]:
def rescale_to_range(value, range_min, range_max,
                  scale_min = 0.0, scale_max = 1.0, 
                  is_strict: bool = True):
    rescaled_value = (value - range_min) / (range_max - range_min) * (scale_max - scale_min) + scale_min 
    if is_strict == True:
        rescaled_value = min(scale_max, max(scale_min, rescaled_value))
    return rescaled_value

In [ ]:
value = 0.75
range_min = 0
range_max = 2
scale_min = 0
scale_max = 1
is_strict = True
new_value = ((value - range_min) / 
             (range_max - range_min) * 
             (scale_max - scale_min) + scale_min)
if is_strict == True:
    new_value = min(scale_max, max(scale_min, new_value))
new_value

When determining the area of concrete to a depth of "c", the total area is the product of this function (<code>is_strict == True</code>) and the area of each individual region.

## 3. Concrete Area Test

In [ ]:
concrete_regions.shape

In [ ]:
def region_count(concrete_regions):
    return concrete_regions.shape[0]

In [ ]:
region_count(concrete_regions)

**TODO** The above function does not work with normal lists or arrays. Need to work out a way to convert lists or 0D arrays to numpy arrays.

In [ ]:
def region_areas(concrete_regions, get_total: bool = False):
    count = region_count(concrete_regions)
    areas = np.zeros(count)
    for i in range(0, count):
        areas[i] = concrete_regions[i][0] * concrete_regions[i][1]
    if get_total == True:
        return sum(areas)    
    else:
        return areas

In [ ]:
# Return a numpy array of the areas of each region

areas = region_areas(concrete_regions)
areas

In [ ]:
# This time return the total area of all the regions using the same function

areas = region_areas(concrete_regions, True)
areas

## 4. Concrete Region Height Test
Need a function that will return an area of the stacked heights of all the concrete regions.

In [ ]:
def region_heights(concrete_regions, total_height: bool = False):
    count = concrete_regions.shape[0]
    heights = np.zeros(count + 1)
    for i in range(1, count + 1):
        heights[i] = heights[i - 1] + concrete_regions[i-1][1]
    if total_height == True:
        return max(heights)
    else:
        return heights

In [ ]:
# By default return an area of the region distances
arr = region_heights(concrete_regions)
arr

In [ ]:
# Return the maximum height of the section using same function
max_height = region_heights(concrete_regions, total_height = True)
max_height

Create a function that calculates the effective area given a user-input "c" value

In [ ]:
c = 10

In [ ]:
def region_heights(concrete_regions, c = math.inf, total_height: bool = False):
    count = concrete_regions.shape[0]
    heights = np.zeros(count + 1)
    for i in range(1, count + 1):
        heights[i] = heights[i - 1] + concrete_regions[i-1][1]
    if total_height == True:
        return max(heights)
    else:
        return heights